# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\"\x7f\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05label\x18\x02 \x01(\t\x12)\n\nattributes\x18\x03 \x03(\x0b\x32\x15.Node.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x84\x01\n\x04\x45\x64ge\x12\x0e\n\x06source\x18\x01 \x01(\x05\x12\x0e\n\x06target\x18\x02 \x01(\x05\x12)\n\nattributes\x18\x03 \x03(\x0b\x32\x15.Edge.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\x05Graph\x12\x14\n\x05nodes\x18\x01 \x03(\x0b\x32\x05.Node\x12\x14\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x05.Edgeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NODE_ATTRIBUTESENTRY']._options = None
  _globals['_NODE_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_EDGE_ATTRIBUTESENTRY']._options = None
  _globals['_EDGE_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_NODE']._serialized_start=15
  _globals['_NODE']._serialized_end=142
  _globals['_NODE_ATTRIBUTESENTRY']._serialized_start=93
  _globals['_NODE_ATTRIBUTESENTRY']._serialized_end=142
  _globals['_EDGE']._serialized_start=145
  _globals['_EDGE']._serialized_end=277
  _globals['_EDGE_ATTRIBUTESENTRY']._serialized_start=93
  _globals['_EDGE_ATTRIBUTESENTRY']._serialized_end=142
  _globals['_GRAPH']._serialized_start=279
  _globals['_GRAPH']._serialized_end=330
# @@protoc_insertion_point(module_scope)
